version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - gocyclo
    - prealloc
  exclusions:
    paths:
      - testdata
    rules:
      - linters: [gocyclo]
        path: _test\.go

formatters:
  exclusions:
    paths:
      - testdata
